module:
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3
baseURL: https://www.andreagrandi.it
languageCode: en-us
title: Andrea Grandi
theme: hugo-theme-stack
schema: true
permalinks:
   page:
     posts: /posts/:slug/
paginate: 5
