main:
- name: Home
  pageRef: /
  weight: 10
- name: About
  pageRef: /about
  weight: 20
- name: Curriculum
  pageRef: /cv
  weight: 30
social:
- identifier: "github"
  name: "GitHub"
  url: "https://github.com/andreagrandi"
  params:
    icon: "brand-github"
- identifier: "mastodon"
  name: "Mastodon"
  url: "https://mastodon.social/@andreagrandi"
  params:
    icon: "brand-mastodon"
