# hugo-theme-stack configuration
mainSections:
  - posts
featuredImageField: image
rssFullContent: true
footer:
  since: 2007
  customText: source code available on <a href="https://github.com/andreagrandi/andreagrandi-hugo">GitHub</a>
sidebar:
  # emoji: 🦕
  subtitle: Software Developer
  avatar:
      enabled: true
      local: false
      src: /about/images/me_pycon_2019_2.jpg
menu:
  main: []

imageProcessing:
  cover:
    enabled: false
  content:
    enabled: false

opengraph:
  enabled: true

widgets:
  homepage:
    - type: "search"
    - type: "archives"
      params:
        limit: 5
    - type: "categories"
      params:
        limit: 5
    - type: "tag-cloud"
      params:
        limit: 10

colorScheme:
  # Display toggle
  toggle: false

  # Available values: auto, light, dark
  default: light

comments:
  enabled: true
  provider: disqus

article:
  readingTime: false
