# mainroad theme configuration
# sidebar:
#   home: right  # Configure layout for home page
#   list: left   # Configure layout for list pages
#   single: false  # Configure layout for single pages
#   # Enable widgets in given order
#   widgets: [search, recent, categories, social, languages]
# logo:
#   subtitle: Software Engineer
# widgets:
#   social:
#     github: andreagrandi
#     mastodon: https://mastodon.social/@andreagrandi
# post_meta:
#   - date
#   - categories
# opengraph: true

# hugo-theme-stack configuration
mainSections:
  - posts
featuredImageField: image
rssFullContent: true
footer:
  since: 2007
  customText:
sidebar:
  # emoji: 🦕
  subtitle: Software Developer
  avatar:
      enabled: true
      local: false
      src: /about/images/me_pycon_2019_2.jpg
menu:
  main: []

imageProcessing:
  cover:
    enabled: false

widgets:
  homepage:
    - type: "search"
    - type: "archives"
      params:
        limit: 5
    - type: "categories"
      params:
        limit: 5
    - type: "tag-cloud"
      params:
        limit: 10
