version: 2.1
orbs:
  hugo: circleci/hugo@1.3.1
executors:
  base-image-executor:
    docker:
      - image: cimg/go:1.22.0
jobs:
  deploy-to-github:
    executor: base-image-executor
    environment:
      BRANCH: master
      TARGET_REPO: andreagrandi/andreagrandi.github.io.git
      HUGO_OUTPUT_FOLDER: public
    steps:
      - attach_workspace:
          at: ~/build
      - run:
          name: "Install system dependencies"
          command: |
            sudo apt-get update && sudo apt-get install -y rsync
      - run:
          name: Deploy static pages to Github Pages
          command: |
            echo -e "Starting to deploy to Github Pages\n"
            # cd ~/repo
            git config --global user.email "builds@circleci.com"
            git config --global user.name "CircleCI"
            # using token clone gh-pages branch
            git clone --quiet --branch=$CIRCLE_BRANCH https://${GH_TOKEN}@github.com/$TARGET_REPO built_website > /dev/null
            # go into directory and copy data we're interested in to that directory
            cd built_website
            echo "rsync built code with checked out code..."
            rsync -r --exclude=.git --delete ../build/$HUGO_OUTPUT_FOLDER/ ./
            # add, commit and push files
            echo "add files to git..."
            git add -f .
            echo "commit files to git repository..."
            if git commit -m "CircleCI build $CIRCLE_BUILD_NUM pushed to Github Pages" ; then
              echo "git push files with force..."
              git push -fq origin $BRANCH > /dev/null
              echo -e "Deploy completed\n"
            else
              echo "Content not changed, nothing to deploy"
            fi

workflows:
  build_and_deploy:
    jobs:
      - hugo/build:
          html-proofer: false
          version: "0.123.3"
      - deploy-to-github:
          requires:
            - hugo/build
          filters:
            branches:
              only:
                - master
